import requests, re, socket, time, concurrent.futures
from datetime import datetime

# المصادر المحدثة (شاملة الروابط الجديدة التي أرسلتها)
SOURCES = [
    "https://cccamcard.com/free-cccam-server.php",
    "https://cccamia.com/cccamfree1/",
    "https://cccam.net/freecccam",
    "https://cccam-premium.pro/free-cccam/",
    "https://raw.githubusercontent.com/yebekhe/TV-Logo/main/cccam.txt",
    "https://raw.githubusercontent.com/mueof/free-cccam/main/cccam.txt",
    "https://vipsat.net/free-cccam-server.php",
    "https://boss-cccam.com/free-cccam-server.php"
]

NCAM_HEADER = """[reader]
label                         = github:SoftCam_AutoUpdate
enable                        = 1
protocol                      = emu
device                        = https://raw.githubusercontent.com/JetCamFastCam/JetFastCamRza/main/SoftCam.Key
group                         = 1

[reader]
label                         = Emulator_Local
enable                        = 1
protocol                      = emu
device                        = emulator
group                         = 1
"""

def verify_server(line):
    line = line.strip()
    # تحسين التعرف على السيرفر (يدعم الفتحات والرموز المختلفة)
    match = re.search(r'C:\s*([a-zA-Z0-9\-\.]+)\s+(\d+)\s+(\S+)\s+(\S+)', line, re.I)
    if not match: return None
    
    host, port, user, passwd = match.groups()
    
    # قائمة الهوستات الممنوعة (تسبب ثقل للجهاز)
    forbidden = ['streamtveuropa', 'nassim', 'visit', 'ugeen', 'test']
    if any(f in host.lower() for f in forbidden): return None

    try:
        start = time.perf_counter()
        # فحص جودة الاتصال بالبورت
        with socket.create_connection((host, int(port)), timeout=1.2) as sock:
            latency = int((time.perf_counter() - start) * 1000)
            if latency < 400: # قبول السيرفرات تحت 400ms
                return (latency, host, port, user, passwd)
    except:
        return None

def run_scraper():
    print(f"📡 بدأت عملية جلب السيرفرات من {len(SOURCES)} مصادر...")
    all_raw = []
    
    with requests.Session() as s:
        s.headers.update({'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'})
        for url in SOURCES:
            try:
                r = s.get(url, timeout=15)
                # استخراج أسطر C: حتى لو كانت داخل كود HTML
                matches = re.findall(r'C:\s*[a-zA-Z0-9\-\.]+\s+\d+\s+\S+\s+\S+', r.text, re.I)
                all_raw.extend(matches)
                print(f"✅ تم سحب {len(matches)} سطر من: {url.split('/')[2]}")
            except Exception as e:
                print(f"❌ خطأ في المصدر {url}: {e}")

    # تصفية المتكرر
    unique_list = list(set(all_raw))
    print(f"🔍 فحص جودة {len(unique_list)} سيرفر حالياً...")

    # الفحص المتعدد الخيوط (سرعة قصوى)
    with concurrent.futures.ThreadPoolExecutor(max_workers=100) as executor:
        results = [r for r in executor.map(verify_server, unique_list) if r]

    # الترتيب حسب الأسرع (Ping أقل)
    results.sort(key=lambda x: x[0])

    # 1. حفظ ملف ncam.server لأجهزة الإنيجما
    with open("ncam.server", "w", encoding="utf-8") as f:
        f.write(f"### GENERATED BY NCAM-HUNT | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} ###\n")
        f.write(NCAM_HEADER)
        
        for i, (lat, host, port, user, passwd) in enumerate(results[:40]): # أفضل 40 سيرفر
            f.write(f"\n[reader]\n")
            f.write(f"label                         = Server_{i+1}_{lat}ms\n")
            f.write(f"protocol                      = cccam\n")
            f.write(f"device                        = {host},{port}\n")
            f.write(f"user                          = {user}\n")
            f.write(f"password                      = {passwd}\n")
            f.write(f"group                         = 1\n")
            f.write(f"cccversion                    = 2.3.2\n")
            f.write(f"ccckeepalive                  = 1\n")

    # 2. حفظ ملف CCcam.cfg التقليدي
    with open("CCcam.cfg", "w", encoding="utf-8") as f:
        for lat, host, port, user, passwd in results[:40]:
            f.write(f"C: {host} {port} {user} {passwd} # Ping: {lat}ms\n")

    print(f"\n✨ اكتملت العملية!")
    print(f"📂 الملفات الجاهزة: ncam.server (لـ Ncam/Oscam) و CCcam.cfg (لـ CCcam)")
    print(f"🚀 تم العثور على {len(results)} سيرفر شغال.")

if __name__ == "__main__":
    run_scraper()
