import requests
import re
import socket
from concurrent.futures import ThreadPoolExecutor

# 1. قائمة المواقع اللي غنجيبو منها (Sources)
SOURCES = [
    "https://cccamcard.com/free-cccam-server.php",
    "https://testcline.com/free-cccam-server.php",
    "https://cccam.premium.pro/free-cccam/",
    "https://cccamia.com/free-cccam/",
    "https://www.cccambird.com/freecccam.php",
    "https://cccamprime.com/cccam48h.php",
    "https://dhoom.org/test/",
    "https://raw.githubusercontent.com/Badr-cx/icone-wegoo/refs/heads/main/CCcam.cfg" # الرابط ديالك حتى هو
]

def server_tester(line):
    """الـ Tester الصارم: كيتأكد من الاتصال وسرعة الاستجابة"""
    # تنقية السطر من أي كود HTML زاید
    line = re.sub(r'<[^>]*>', '', line).strip()
    
    # التأكد من فورمات السطر (C: Host Port User Pass)
    match = re.search(r'([CN]:\s*\S+\s+\d+\s+\S+\s+\S+)', line)
    if not match:
        return None
    
    clean_line = match.group(1)
    try:
        parts = clean_line.split()
        host = parts[1]
        port = int(parts[2].replace(',', ''))
        
        # اختبار الاستجابة السريعة (Timeout قصير جدا للثبات)
        with socket.create_connection((host, port), timeout=0.7):
            return clean_line
    except:
        return None

def main():
    all_raw_lines = []
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}

    print("--- 🛠️ الماكينة بدات خدامة: جاري جمع السيرفرات ---")
    
    for url in SOURCES:
        try:
            r = requests.get(url, headers=headers, timeout=10)
            # استخراج السطور بـ Regex احترافي
            found = re.findall(r'[CN]:\s?\S+\s\d+\s\S+\s\S+', r.text)
            all_raw_lines.extend(found)
            print(f"✅ تم السحب من: {url.split('/')[2]} ({len(found)} سطر)")
        except:
            print(f"❌ فشل السحب من: {url.split('/')[2]}")

    # حيد المعاودين قبل ما نبداو التيست
    unique_lines = list(set(all_raw_lines))
    print(f"\n🔍 الإجمالي المجموع: {len(unique_lines)} سطر. جاري الاختبار الصارم (Tester)...")

    # فحص 100 سطر فدقة واحدة للسرعة
    with ThreadPoolExecutor(max_workers=100) as executor:
        results = list(executor.map(server_tester, unique_lines))

    online_servers = [s for s in results if s]

    # حفظ السيرفرات "القرطاسة" فقط
    with open("CCcam.cfg", "w") as f:
        f.write("# 🤖 Generated by Gemini Auto-Tester\n")
        f.write("# 📅 Last Update: 2026\n\n")
        for s in online_servers:
            f.write(s + "\n")

    print(f"\n--- ✨ النتيجة النهائية ---")
    print(f"✅ بقاو غير {len(online_servers)} سيرفر ناضيين من أصل {len(unique_lines)}.")
    print("🚀 الملف CCcam.cfg دابا واجد ونقي فـ GitHub.")

if __name__ == "__main__":
    main()
