import requests
import re
import socket
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor

# المصادر والرابط ديالك
SOURCES = [
    "https://cccamcard.com/free-cccam-server.php",
    "https://testcline.com/free-cccam-server.php",
    "https://cccam.premium.pro/free-cccam/",
    "https://cccamia.com/free-cccam/",
    "https://www.cccambird.com/freecccam.php",
    "https://cccamprime.com/cccam48h.php",
    "https://dhoom.org/test/",
    "https://raw.githubusercontent.com/Badr-cx/icone-wegoo/refs/heads/main/CCcam.cfg"
]

def server_tester(line):
    line = re.sub(r'<[^>]*>', '', line).strip()
    match = re.search(r'([CN]:\s*\S+\s+\d+\s+\S+\s+\S+)', line)
    if not match: return None
    
    clean_line = match.group(1)
    try:
        parts = clean_line.split()
        host, port = parts[1], int(parts[2].replace(',', ''))
        # فحص صارم (0.7 ثانية) لضمان الجودة
        with socket.create_connection((host, port), timeout=0.7):
            return clean_line
    except:
        return None

def main():
    # جلب تاريخ اليوم
    today_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    all_raw_lines = []
    headers = {'User-Agent': 'Mozilla/5.0'}

    print(f"--- 🛠️ بدء التحديث ليوم: {today_date} ---")
    
    for url in SOURCES:
        try:
            r = requests.get(url, headers=headers, timeout=10)
            found = re.findall(r'[CN]:\s?\S+\s\d+\s\S+\s\S+', r.text)
            all_raw_lines.extend(found)
        except: continue

    unique_lines = list(set(all_raw_lines))
    
    with ThreadPoolExecutor(max_workers=100) as executor:
        results = list(executor.map(server_tester, unique_lines))

    online_servers = [s for s in results if s]

    # كتابة الملف مع التاريخ
    with open("CCcam.cfg", "w") as f:
        f.write(f"# 📅 Last Update: {today_date}\n")
        f.write(f"# ✅ Total Online Servers: {len(online_servers)}\n")
        f.write("# 🤖 Auto-generated by Gemini Tester\n\n")
        for s in online_servers:
            f.write(s + "\n")

    print(f"✅ تم التحديث بنجاح! {len(online_servers)} سيرفر شغال.")

if __name__ == "__main__":
    main()
