name: Universal Icone Packer

on:
  workflow_dispatch: # كتخدميه بيدك ملي ترفعي الملف

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unrar zip unzip

      - name: Auto Extract and Permission Fix
        run: |
          # 1. البحث عن أي ملف مضغوط (rar, zip, tar.gz)
          COMPRESSED_FILE=$(ls *.rar *.zip *.tar.gz 2>/dev/null | head -n 1)
          
          if [ -z "$COMPRESSED_FILE" ]; then
            echo "Error: No compressed file found in repository!"
            exit 1
          fi
          
          echo "Processing file: $COMPRESSED_FILE"
          mkdir -p output_folder

          # 2. فك الضغط على حسب النوع
          if [[ $COMPRESSED_FILE == *.rar ]]; then
            unrar x "$COMPRESSED_FILE" output_folder/
          elif [[ $COMPRESSED_FILE == *.zip ]]; then
            unzip "$COMPRESSED_FILE" -d output_folder/
          else
            tar -xzvf "$COMPRESSED_FILE" -C output_folder/
          fi

          # 3. تطبيق صلاحيات الروت والمجموعات (0:0)
          # هاد السطر هو اللي كيخلي الأيكون يقبل البلوجين
          sudo chown -R root:root output_folder/
          sudo chmod -R 755 output_folder/

          # 4. التجميع بصيغة .ngz مع الحفاظ على الصلاحيات
          cd output_folder/
          # استخدام --owner=0 لضمان الروت حتى لو تغير السيرفر
          sudo tar --owner=0 --group=0 -cvzf ../Plugin_Root_Ready.ngz *

      - name: Upload Final Plugin
        uses: actions/upload-artifact@v3
        with:
          name: Icone-Plugin-Package
          path: Plugin_Root_Ready.ngz
