name: Wolf Universal Packer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract and Fix Root
        run: |
          # 1. فك ضغط الملف الأصلي
          tar -xvf plugin-wolf.tar

          # 2. تطبيق صلاحيات الروت والمجموعات (0:0)
          # هاد الخطوة هي اللي كتحل مشكل Permission Denied فـ الأيكون
          sudo chown -R root:root plugin-wolf/
          sudo chmod -R 755 plugin-wolf/

          # 3. التجميع بصيغة .ngz اللي كيقبلها الجهاز
          cd plugin-wolf/
          sudo tar --owner=0 --group=0 -cvzf ../Plugin_Verified_Root.ngz *

      - name: Upload Final Plugin
        uses: actions/upload-artifact@v3
        with:
          name: Icone-Plugin-Final
          path: Plugin_Verified_Root.ngz
