name: Test GitHub Scraper

on:
  workflow_dispatch: # باش تخدمو بيدك

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ضروري باش GitHub يقدر يحط الملف فـ الـ Repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ncam.server
          git commit -m "Update ncam.server with new servers" || echo "No changes to commit"
          git push
