name: Auto Update Ncam Server

on:
  schedule:
    - cron: '0 1 * * *' # يشتغل تلقائياً كل يوم مع الواحدة صباحاً
  workflow_dispatch:   # يسمح لك بتشغيله يدوياً من زر Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Chrome and Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          pip install selenium webdriver-manager

      - name: Run Scraper Script
        run: python scraper.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ncam.server
          # سيقوم بالتحديث فقط إذا وجد تغييرات في الملف
          git commit -m "Update ncam.server - $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
